tcx_account_accountpage:
    pattern:  /tcxaccount
    defaults: { _controller: TcxAccountBundle:TcxAccount:index }

tcx_account_homepage:
    pattern: /
    defaults : { _controller: TcxAccountBundle:TcxAccount:index}
    
