parameters:
#    tcx_account.example.class: Tcx\Bundle\TcxAccountBundle\Example

services:
#    tcx_account.example:
#        class: %tcx_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
