parameters:
    tcxAccountRepository.class: Tcx\Bundle\TcxAccountBundle\Repository\TcxAccountRepository
    tcxAccountController.class: Tcx\Bundle\TcxAccountBundle\Controller\TcxAccountController

services:
  tcxAccountServiceRepository: 
    class: "%tcxAccountRepository.class%"
    factory_service: doctrine.orm.default_entity_manager 
    factory_method: getRepository
    arguments: ["TcxAccountBundle:TcxAccount"]
    
  tcxAccountServiceController:
    class: "%tcxAccountController.class%"
    calls:
            - [setTcxAccountRepository, ["@tcxAccountServiceRepository"]]