parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: tchaxstuces-v2
    database_user: root
    database_password: tsounekwol
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 0d07c43951c663bc19420f4e30feb031f2861a16
    database_path: null

