<?php

namespace Tcx\Bundle\TcxAccountBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Tcx\Bundle\TcxAccountBundle\Entity\TcxAccount;

/**
 * TcxAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TcxAccountRepository extends EntityRepository
{
	/**
	 * Persits an entity in database 
	 * 
	 * @param TcxAccount $tcxAccount
	 * 		The TcxAccount entity 
	 */
	public function save(TcxAccount $tcxAccount) {
		$em = $this->getEntityManager();
		$em->persist($tcxAccount);
		$em->flush();
	}
	
	/**
	 * Deletes an entity in database
	 * 
	 * @param TcxAccount $tcxAccount
	 * 		The entity to delete
	 */
	public function delete(TcxAccount $tcxAccount) {
		$em = $this->getEntityManager();
		$em->remove($tcxAccount);
		$em->flush();
	}

	
}
